[package]
name = "bibtex-parser"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
authors = ["Ayan Das <bvits@riseup.net>"]
description = "Yet another bibtex-parser"
documentation = "https://docs.rs/bibtex-parser"
repository = "https://github.com/b-vitamins/bibtex-parser"
readme = "README.md"
keywords = ["bibtex", "parser", "latex", "bibliography", "citation"]
categories = ["parser-implementations", "text-processing"]
license = "MIT OR Apache-2.0"

[features]
default = []
parallel = ["rayon"]


[dependencies]
winnow = "0.5"
thiserror = "1.0"
memchr = "2.7"
ahash = "0.8"
rayon = { version = "1.8", optional = true }
unicode-normalization = "0.1"
backtrace = "0.3"
serde_json = "1.0.140"
chrono = "0.4.41"
lazy_static = "1.5.0"
serde = "1.0.219"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
pretty_assertions = "1.4"
insta = { version = "1.34", features = ["yaml"] }
proptest = "1.4"
rand = "0.8"
nom-bibtex = "0.3"


[[bench]]
name = "performance"
harness = false

[[bench]]
name = "memory"
harness = false

[[bench]]
name = "delimiter"
harness = false

[[bench]]
name = "parallel"
harness = false
required-features = ["parallel"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[profile.bench]
inherits = "release"
debug = true
strip = false
opt-level = 3
lto = "fat"
codegen-units = 1
